In [ ]:
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [ ]:
def quadrant(o, a):

  def invtan(o, a):
    return np.abs(np.arctan(o / a))

  theta = np.where(o > 0,
                      np.where(a > 0,
                                invtan(o, a),
                      np.where(a < 0,
                                np.pi - invtan(o, a), np.NaN)),
          np.where(o < 0,
                      np.where(a < 0,
                                np.pi + invtan(o, a),
                      np.where(a > 0,
                                invtan(o, a) * -1,
                      np.NaN)),
          np.NaN))

      #print("o = "+np.array2string(o))
      #print("a = "+np.array2string(a))
      #print('theta = '+np.array2string(theta))
      #print()
      #print()

  return theta

In [ ]:
origin = np.transpose(np.array([0, 0, 0]))
#axes = np.array([[5, 5, -np.sqrt(5)], [5, -np.sqrt(5), 5], [-np.sqrt(5), 5, 5]])
axes = np.array([[5, 0.01, 0.01], [0.01, 5, 0.01], [0.01, 0.01, 5]])

phi_z = - np.pi / 4
phi_x = - np.pi / 4

axes_ph = np.empty(axes.shape)


## x-axis rotation
h_yz = np.linalg.norm(axes[1:, :], axis=0)
theta_yz = quadrant(axes[2, :], axes[1, :])
r_theta_yz = theta_yz - phi_x

axes_ph[1, :] = h_yz * np.cos(r_theta_yz)#r_theta_yxy)  # y coordinates
axes_ph[2, :] = h_yz * np.sin(r_theta_yz)#r_theta_zyz)  # z coordinates


## z-axis rotation
h_xy = np.linalg.norm(axes_ph[0:2, :], axis=0)
theta_xy = quadrant(axes_ph[1, :], axes_ph[0, :])
r_theta_xy = theta_xy - phi_z

axes_ph[0, :] = h_xy * np.cos(r_theta_xy)#r_theta_yxy)  # x coordinates
axes_ph[1, :] = h_xy * np.sin(r_theta_xy)#r_theta_yxy)  # y coordinates

## y-axis rotation
#h_xz = np.linalg.norm(np.vstack((axes[0, :], axes[2, :])), axis=0)
#theta_xz = quadrant(axes[0, :], axes[2, :])
#r_theta_zxz = theta_zxz


# Probably incorrect
#axes_ph[0, :] = h_xy * np.sin(r_theta_xy)#r_theta_yxy)  # x coordinates
#axes_ph[1, :] = h_xy * np.cos(r_theta_xy)#r_theta_yxy)  # y coordinates
#axes_ph[2, :] = h_xz * np.cos(r_theta_yz)#r_theta_zyz)  # z coordinates

In [ ]:
fig = go.Figure()
fig.add_trace(go.Scatter3d(x=[0], y=[0], z=[0], name='origin', line={'color': 'orange'}))
fig.add_trace(go.Scatter3d(x=[origin[0], axes[0, 0]], y=[origin[1], axes[1, 0]], z=[origin[2], axes[2, 0]], name='x-axis', line={'color': 'red', 'width': 4}, marker={'opacity': 0}))
fig.add_trace(go.Scatter3d(x=[origin[0], axes[0, 1]], y=[origin[1], axes[1, 1]], z=[origin[2], axes[2, 1]], name='y-axis', line={'color': 'green', 'width': 4}, marker={'opacity': 0}))
fig.add_trace(go.Scatter3d(x=[origin[0], axes[0, 2]], y=[origin[1], axes[1, 2]], z=[origin[2], axes[2, 2]], name='z-axis', line={'color': 'blue', 'width': 4}, marker={'opacity': 0}))
#fig.update_layout(scene={'xaxis': {'autorange': 'reversed'}})
#fig.update_layout(xaxis=dict(autorange='reversed'))  # Reverse the x-axis
fig.show()

fig2 = go.Figure()
fig2.add_trace(go.Scatter3d(x=[0], y=[0], z=[0], name='origin', line={'color': 'orange'}))
fig2.add_trace(go.Scatter3d(x=[origin[0], axes_ph[0, 0]], y=[origin[1], axes_ph[1, 0]], z=[origin[2], axes_ph[2, 0]], name='x-axis', line={'color': 'red', 'width': 4}, marker={'opacity': 0}))
fig2.add_trace(go.Scatter3d(x=[origin[0], axes_ph[0, 1]], y=[origin[1], axes_ph[1, 1]], z=[origin[2], axes_ph[2, 1]], name='y-axis', line={'color': 'green', 'width': 4}, marker={'opacity': 0}))
fig2.add_trace(go.Scatter3d(x=[origin[0], axes_ph[0, 2]], y=[origin[1], axes_ph[1, 2]], z=[origin[2], axes_ph[2, 2]], name='z-axis', line={'color': 'blue', 'width': 4}, marker={'opacity': 0}))
fig2.show()

In [ ]:
test = np.array([[3, 5, 8], [99, 99, 99], [4, 12, 15]])
selection = test[1:, :]
result = np.linalg.norm(selection, axis=0)
print(selection)
print(result)

[[99 99 99]
 [ 4 12 15]]
[ 99.08077513  99.72462083 100.12991561]
